version: '3'

volumes:
  pg_data_production:
  static_volume:
  media_volume:
services:
  db:
    image: postgres:13
    restart: always
    env_file: .env
    volumes:
      - pg_data_production:/var/lib/postgresql/data
  backend:
    image: ${DOCKER_USERNAME}/kittygram_backend
    restart: always
    env_file: .env
    volumes:
      - static_volume:/backend_static
      - media_volume:/app/media
  frontend:
    env_file: .env
    image: ${DOCKER_USERNAME}/kittygram_frontend
    restart: always
    command: cp -r /app/build/. /frontend_static/
    volumes:
      - static_volume:/frontend_static
  gateway:
    image: ${DOCKER_USERNAME}/kittygram_gateway
    restart: always
    env_file: .env
    depends_on:
      - db
    ports:
      - 9000:80
    volumes:
      - static_volume:/staticfiles/
      - media_volume:/media
